"""empty message

Revision ID: 379ce97059fc
Revises: 62706d21a054
Create Date: 2024-02-21 23:25:23.323623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '379ce97059fc'
down_revision = '62706d21a054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('heure_deb', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('heure_fin', sa.Time(), nullable=True))
        batch_op.drop_column('date_deb')
        batch_op.drop_column('date_fin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_deb', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('heure_fin')
        batch_op.drop_column('heure_deb')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
