"""empty message

Revision ID: 62706d21a054
Revises: 76030d64e062
Create Date: 2024-02-18 22:32:53.732949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62706d21a054'
down_revision = '76030d64e062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('information', sa.String(), nullable=True))
        batch_op.drop_column('code_to_execute')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_to_execute', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('information')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
