"""empty message

Revision ID: 76030d64e062
Revises: 
Create Date: 2024-02-17 23:19:30.906764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76030d64e062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('type_user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_deb', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('schemas_board', sa.String(), nullable=True),
    sa.Column('code_to_execute', sa.String(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composants_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_composant', sa.Integer(), nullable=True),
    sa.Column('id_reservation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_composant'], ['composants.id'], ),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composants_reservation')
    op.drop_table('reservations')
    op.drop_table('users')
    op.drop_table('composants')
    # ### end Alembic commands ###
