"""empty message

Revision ID: cb49a343923f
Revises: 
Create Date: 2024-02-23 14:16:40.476611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb49a343923f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('type_user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('heure_deb', sa.Time(), nullable=True),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('descriptions', sa.String(), nullable=True),
    sa.Column('schemas_board', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composants_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_composant', sa.Integer(), nullable=True),
    sa.Column('id_reservation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_composant'], ['composants.id'], ),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composants_reservation')
    op.drop_table('reservations')
    op.drop_table('users')
    op.drop_table('composants')
    # ### end Alembic commands ###
